### ISSUE TITLE
Great work 👍

### ISSUE THREAD

**Issue by jamiecoe** [FACN8/JS_Quiz_INF#16]
Impressive stuff! Some interesting quiz questions - `What is time? Never` 😂 

I'm very please to see these things:
- Dividing logic into functions - this is very helpful for readability, code is nicely grouped into functions which describe what it's doing. Keep it up!
- Nice use of `setInterval` function for countdown
- Mobile first design 

What's the sound button supposed to do??

**Comment by LogicX1** [comment]
Now you can enjoy the quiz with sounds ! How awesome !
